### PR TITLE
OHRM5X-2486: Bump FE libraries to latest minor version

### PR DESCRIPTION
**Pull request by devishke-orange**
PR contains:
- OHRM5X-2486: [FE]  Update libraries with security alerts

~Only libraries with security alerts (and their dependencies) were bumped using `yarn up -R` (excluding axios).~

Security libraries were updated first using `yarn up -R` (excluding axios). Then yarn was set to version 4.1.0. Remaining libraries were upgraded to latest minor version using `yarn upgrade-interactive`.

### CODE REVIEW

**Comment by Super-Chama** [comment]
@devishke-orange I've been meaning to bump up dependencies inside of installer but never had a chance. Perhaps you can do that also here? Also update browserlist db

**Comment by devishke-orange** [comment]
@Super-Chama yes working on it. I'm thinking of updating yarn version also.

I did some testing with Cypress 13 as well and got it working. Will inform you once I make a PR

**Review by Super-Chama — APPROVED** [review]
Thanks for updating this. long time due work

**Comment by devishke-orange** [comment]
@RajithaKumara Please take a look since there are a lot of changes.

**Review by RajithaKumara — APPROVED** [review]

**Pull request merged**
